### ISSUE TITLE
Face recognition not working properly on part

### ISSUE THREAD

**Issue by Tyler-Heckenlively** [tetonsim/pywim#79] opened 2021-02-15 17:20 UTC
The cylindrical face recognition only selects areas of the cylinder and not the entire cylinder.

![image](https://user-images.githubusercontent.com/69323579/107976531-f4463d00-6f76-11eb-93a1-0ef7b2ffd0cc.png)
![image](https://user-images.githubusercontent.com/69323579/107976546-f9a38780-6f76-11eb-94b1-2ba8d61ca80b.png)

[Flag Pole Holder V2.zip](https://github.com/tetonsim/pywim/files/5983120/Flag.Pole.Holder.V2.zip)

**Comment by Tyler-Heckenlively** [comment] 2021-02-15 17:37
For trouble shooting purposes i have added a flat bottom to this cylinder and the surface recognition works perfect (Flag Pole Holder V3). I also added a rounded end to the cylinder and that resulted in no surface selection on the cylinder (Flag Pole Holder V4).

Flag Pole Holder V3:
![image](https://user-images.githubusercontent.com/69323579/107977806-fc06e100-6f78-11eb-8d0a-f427e6d9e1ed.png)
[Flag Pole Holder V3.zip](https://github.com/tetonsim/pywim/files/5983195/Flag.Pole.Holder.V3.zip)

Flag Pole Holder V4:
![image](https://user-images.githubusercontent.com/69323579/107978146-8cddbc80-6f79-11eb-9249-ca688ef84099.png)
[Flag Pole Holder V4.zip](https://github.com/tetonsim/pywim/files/5983183/Flag.Pole.Holder.V4.zip)

**Comment by dougkenik** [comment] 2021-02-15 17:49
Duplicate of #62

**Closed by dougkenik** 2021-02-15 17:49 UTC
